version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./docker:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://localhost:9090
  
  worker:
    image: locustio/locust
    volumes:
      - ./docker:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
